### ISSUE TITLE
Iss : 채팅방 액티비티에서 메시지 전송 시 간헐적으로 발생하는 전송 씹힘 문제 & 전송 성능 관련

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-FrontEnd#13]
채팅방 액티비티에서 간헐적으로 전송이 씹히고 데이터가 많아질 수록 전송이 느려지는 (데이터가 많아져서 느려지는 지는 불확실) 현상에 대한 해결이 필요
- 채팅 전송과정과 수신과정을 다시 한번 살펴보고 문제점을 명확히 정의 후 해결이 요구 됌

**Comment by Libienz** [comment]
간헐적으로 메시지 전송이 씹힐 때 서버에러가 java.time.format.DateTimeParseException로 찍히는 지 유심히 확인해봐야 함 현재 내 환경에서는 전송이 안되는 그 순간에 저 로그가 떴음
- 해당 에러는 LocalDateTime을 역직렬화 할 때 발생하는 문제라고 함 
- 특정 시간에 시간의 길이라던지 다른 특수한 이유로 form이 망가지면 전송이 씹히는 현상일 수도 있겠다는 생각이 듦

**에러 상황 캡처**  
![image](https://github.com/Libienz/Spoot-Taxi-FrontEnd/assets/85234650/9b527cf8-7621-45c5-9f5d-485a210167c9)

**Comment by ks0927** [comment]
> 간헐적으로 메시지 전송이 씹힐 때 서버에러가 java.time.format.DateTimeParseException로 찍히는 지 유심히 확인해봐야 함 현재 내 환경에서는 전송이 안되는 그 순간에 저 로그가 떴음
> 
> * 해당 에러는 LocalDateTime을 역직렬화 할 때 발생하는 문제라고 함
> * 특정 시간에 시간의 길이라던지 다른 특수한 이유로 form이 망가지면 전송이 씹히는 현상일 수도 있겠다는 생각이 듦
> 
> **에러 상황 캡처** ![image](https://user-images.githubusercontent.com/85234650/258504143-9b527cf8-7621-45c5-9f5d-485a210167c9.png)

어디 문제인지 확인했습니다. 아마 
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2023-08-06T15:42": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2023-08-06T15:42' could not be parsed at index 16

서버에서 이런 문제가 있었을텐데요. 프론트에서 보내는 LocalDateTime의 형식이 서버의 형식과 다를때 발생하고있습니다.
정확하게는 2023-08-06T15:42:00 이렇게 발송되어 왔어야 했는데 현재 초 단위가 짤리고있죠. 정각일때 생략하는 문제 인것같습니다.

**Comment by ks0927** [comment]
@Libienz 
위에 말한바와 같이 초가 00 단위일때  생략되는것 같습니다.
[https://stackoverflow.com/questions/63902489/how-to-get-the-current-localdatetime-including-seconds-with-localdatetime-now](url)
를 참조해주세요
이제 해결방법은 두가지가 있는데요 
첫번째로 기존 LocalDateTime의 형식에서 밀리초를 추가한 "yyyy-MM-dd'T'HH:mm:ss.SS" 이런형태로 보내고 서버도 저런형태로 저장하면 초 단위가 00이여도 생략되지 않습니다.
두번째는 밀리초를 추가할바에 그냥 초단위를 날려버리는겁니다. "yyyy-MM-dd'T'HH:mm" 이렇게 말이죠

어떤 방식이 좋을지 이야기 해주시면 감사하겠습니다. 
그리고 전송 성능에 관한 내용은 아직 잘 모르겠습니다. 약 200개 가량의 메세지를 한 채팅방에서 사용해봤으나 느려짐 현상을 보기 어려웠습니다.

**Comment by Libienz** [comment]
@ks0927  
무슨말인지 이해했음. 카카오톡, 디스코드와 같은 채팅방을 봤을 때 초 단위의 시간을 기록하는 경우는 많이 없는 것 같은데 초단위를 잘라버리는 두번째 방법이 좋지 않을까 생각함
